"""
escalate — Sends a priority escalation alert when automated strategy fails.
Used when price reduction did not recover sales after sufficient time.
"""

import os
import uuid
from datetime import datetime, timezone

import boto3
from dotenv import load_dotenv

load_dotenv()

AWS_REGION     = os.getenv("AWS_REGION", "eu-central-1")
AUDIT_TABLE    = os.getenv("DYNAMODB_AUDIT_TABLE", "heweso-audit-log")
SES_SENDER     = os.getenv("SES_SENDER_EMAIL", "metehanklcl03@gmail.com")
SES_RECIPIENT  = os.getenv("SES_RECIPIENT_EMAIL", "metehanklcl03@gmail.com")

_dynamodb = boto3.resource("dynamodb", region_name=AWS_REGION)
_ses      = boto3.client("ses", region_name=AWS_REGION)
_audit    = _dynamodb.Table(AUDIT_TABLE)


def escalate(product_id: str, reason: str, context: str = "") -> dict:
    """
    Sends a high-priority escalation email and logs ESCALATION to audit.

    Use when:
    - Price reduction did not recover sales (OUTCOME_FAILED)
    - Same product failed multiple times in a row
    - Automated strategy is exhausted

    Args:
        product_id: Product that failed
        reason:     Why escalation is triggered
        context:    Additional analytics context (e.g. failure count, history)

    Returns:
        {"success": bool, "log_id": str, "message_id": str}
    """
    now = datetime.now(timezone.utc).isoformat()

    subject = f"🚨 ESCALATION — {product_id} | Human Action Required"
    body_html = f"""
<html><body style="font-family:Arial,sans-serif;background:#f9fafb;padding:20px">
<div style="max-width:600px;margin:auto;background:#fff;border-radius:8px;
            border-top:4px solid #ef4444;padding:24px">

  <h2 style="color:#ef4444;margin-top:0">🚨 Escalation Alert</h2>
  <p style="color:#6b7280;font-size:14px">
    The autonomous pricing agent has exhausted its automated strategy for this product.
    <strong>Human intervention is required.</strong>
  </p>

  <table style="width:100%;border-collapse:collapse;margin:16px 0">
    <tr style="background:#fef2f2">
      <td style="padding:8px 12px;font-weight:bold;color:#374151;width:140px">Product</td>
      <td style="padding:8px 12px;color:#111827">{product_id}</td>
    </tr>
    <tr>
      <td style="padding:8px 12px;font-weight:bold;color:#374151">Triggered At</td>
      <td style="padding:8px 12px;color:#111827">{now}</td>
    </tr>
    <tr style="background:#fef2f2">
      <td style="padding:8px 12px;font-weight:bold;color:#374151">Reason</td>
      <td style="padding:8px 12px;color:#111827">{reason}</td>
    </tr>
  </table>

  {f'''
  <div style="background:#f3f4f6;border-radius:6px;padding:12px;margin:16px 0">
    <strong style="color:#374151">Analytics Context:</strong>
    <p style="color:#6b7280;margin:8px 0 0;font-size:13px;white-space:pre-wrap">{context}</p>
  </div>
  ''' if context else ''}

  <div style="background:#fef2f2;border-radius:6px;padding:12px;margin-top:16px">
    <strong style="color:#ef4444">Suggested Actions:</strong>
    <ul style="color:#6b7280;font-size:13px;margin:8px 0 0;padding-left:20px">
      <li>Review current pricing strategy manually</li>
      <li>Check if competitor pricing is structural (not a flash sale)</li>
      <li>Consider promotional campaign or bundle offer</li>
      <li>Evaluate product visibility and listing quality</li>
    </ul>
  </div>

  <p style="color:#9ca3af;font-size:11px;margin-top:20px;border-top:1px solid #e5e7eb;padding-top:12px">
    This escalation was automatically generated by the Heweso autonomous pricing agent.
  </p>
</div>
</body></html>
"""

    # Send email
    try:
        email_resp = _ses.send_email(
            Source=SES_SENDER,
            Destination={"ToAddresses": [SES_RECIPIENT]},
            Message={
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {"Html": {"Data": body_html, "Charset": "UTF-8"}},
            },
        )
        message_id = email_resp["MessageId"]
        email_ok   = True
    except Exception as e:
        message_id = str(e)
        email_ok   = False

    # Log to audit
    log_id = str(uuid.uuid4())
    _audit.put_item(Item={
        "log_id":        log_id,
        "timestamp":     now,
        "product_id":    product_id,
        "action":        "ESCALATION",
        "old_value":     "N/A",
        "new_value":     "N/A",
        "reason":        reason,
        "agent_decision": context[:500] if context else "",
    })

    return {
        "success":    email_ok,
        "log_id":     log_id,
        "message_id": message_id,
        "message":    f"Escalation logged and email {'sent' if email_ok else 'failed'}.",
    }


if __name__ == "__main__":
    result = escalate(
        product_id="PROD-001",
        reason="Price reduction did not recover sales after 90 minutes.",
        context="This product has failed 3 times in the last 24 hours."
    )
    print(result)
