"""
send_email — Sends an email to the admin via Amazon SES.
"""

import os

import boto3
from botocore.exceptions import ClientError
from dotenv import load_dotenv

load_dotenv()

AWS_REGION = os.getenv("AWS_REGION", "eu-central-1")
SENDER = os.getenv("SES_SENDER_EMAIL", "agent@heweso.com")
DEFAULT_RECIPIENT = os.getenv("SES_RECIPIENT_EMAIL", "admin@heweso.com")

_ses = boto3.client("ses", region_name=AWS_REGION)


def send_email(subject: str, body: str, recipient: str = "", html_override: str = "") -> dict:
    """
    Sends an HTML-enabled email.

    RECIPIENT GUARD (single source of truth): the destination is ALWAYS the
    verified SES_RECIPIENT_EMAIL from .env. The `recipient` parameter is kept
    only for backward compatibility with existing callers, but it is
    intentionally IGNORED — no caller (Bedrock agent, MCP server, or any
    future one) can redirect mail to an arbitrary address. Keeping the guard
    here, inside the tool, means every caller is protected by construction.

    If html_override is given, it's sent as-is (used by report emails that
    build their own full HTML with tables) instead of auto-wrapping `body`.

    Returns:
        {
            "success": bool,
            "message_id": str | None,
            "error": str | None,
        }
    """
    # Recipient is always the verified address from .env — the caller-supplied
    # `recipient` is intentionally ignored (safe even outside the SES sandbox).
    to_address = DEFAULT_RECIPIENT
    html_body = html_override or _wrap_html(subject, body)

    try:
        response = _ses.send_email(
            Source=SENDER,
            Destination={"ToAddresses": [to_address]},
            Message={
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {
                    "Text": {"Data": body, "Charset": "UTF-8"},
                    "Html": {
                        "Data": html_body,
                        "Charset": "UTF-8",
                    },
                },
            },
        )
        return {
            "success": True,
            "message_id": response["MessageId"],
            "error": None,
        }
    except ClientError as e:
        return {
            "success": False,
            "message_id": None,
            "error": e.response["Error"]["Message"],
        }


def _wrap_html(subject: str, body: str) -> str:
    """Wraps plain-text body in a simple HTML email template."""
    lines = body.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    paragraphs = "".join(f"<p>{line}</p>" for line in lines.splitlines() if line.strip())
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{subject}</title></head>
<body style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px">
  <h2 style="color:#c0392b">🤖 Heweso Pricing Agent</h2>
  <h3>{subject}</h3>
  <div style="background:#f9f9f9;padding:16px;border-left:4px solid #c0392b">
    {paragraphs}
  </div>
  <p style="color:#888;font-size:12px;margin-top:24px">
    This email was automatically generated by the Heweso autonomous pricing agent.
  </p>
</body>
</html>"""


if __name__ == "__main__":
    result = send_email(
        subject="[TEST] Price Updated — Samsung Galaxy S24",
        body=(
            "Product: Samsung Galaxy S24 (PROD-001)\n"
            "Old price: 24999 TL\n"
            "New price: 23499 TL\n"
            "Reason: Matched Trendyol price.\n"
        ),
    )
    print(result)
